### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [magipamies/qgis_BuscaRecursos_pluguin#1]
@magipamies Can you please give small description in English of what the plugin does

**Comment by magipamies** [comment]
Hi, I have just finished updating README file.
You can translate it like "Resources finder" 

BuscaRecursos is a QGis plugin to look for city amenities near a defined facility. Given a circular area defined by a facility (center) and a maximum distance (radius), plugin generates a points layer over OpenStreetMap map with all the target amenity instances found inside this area.

**Comment by magipamies** [comment]
@NyakudyaA have you seen the updated  README file?
